import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    // No need for vite-tsconfig-paths plugin (Vite resolves tsconfig paths natively).
    tsconfigPaths: true,
    // Next 16 requires resolving next/server as next/server.js, but
    // next-auth 5.0.0-beta imports bare "next/server" and fails ESM resolution.
    // Normalize to the .js form via alias for tests only.
    alias: {
      "next/server": "next/server.js",
    },
  },
  test: {
    // Exclude test files copied into build artifacts (dist/, .next/standalone)
    // from collection. These are temporary copies generated by pack:exe.
    exclude: ["**/node_modules/**", "**/dist/**", "**/.next/**"],
    environment: "jsdom",
    // Route Handler / lib tests switch to the node environment via a
    // `// @vitest-environment node` comment at the top of each file
    // (environmentMatchGlobs was removed in Vitest 4).
    setupFiles: ["./vitest.setup.ts"],
    // Tests that call the real API take time, so allow extra headroom.
    testTimeout: 30_000,
    // Run once and exit without watching (for CI / one-shot verification).
    // Use `bun run test -- --watch` to enable watch mode.
    // sharp / @xenova/transformers native modules crash workers in the
    // forks pool, so use the threads pool.
    pool: "threads",
    // next-auth imports bare "next/server" but Next 16's exports require
    // "next/server.js". Aliases only apply to modules Vite transforms, so
    // inline next-auth as an SSR transform target to make the alias apply.
    server: {
      deps: {
        inline: ["next-auth"],
      },
    },
  },
});